= Configure Sync Gateway
:page-type: procedural
:page-layout: article
:page-role: -toc
:page-status: beta
include::partial$_attributesLocal.adoc[]

:idprefix:
:idseparator: -

The following steps explain how to connect Sync Gateway to the Couchbase Server instance.

* Open a new file called *sync-gateway-config.json* with the following.
+
[{tabs}]
====
Default::
+
--
[source,javascript]
----
include::{examplesdir}/getting-started/sync-gateway-config.json[]
----
Configuration properties:

<1> The user's username that you created on the Couchbase Server Admin Console.
<2> The user's password that you created on the Couchbase Server Admin Console.
<3> The xref:shared-bucket-access.adoc[shared bucket access] feature allows Couchbase Server SDKs to also perform operations on this bucket.
<4> `num_index_replicas` is the number of index replicas stored in Couchbase Server, introduced with xref:indexing.adoc[GSI/N1QL indexing].
If you're running a single Couchbase Server node for development purposes the `num_index_replicas` must be set to `0`.
--

With Import Filter::
+
--
For clusters with a large amount of data, the initial import process can take considerable time to complete.
Therefore, to get started with a cluster which contains a large number of pre-existing documents, we recommend to use an `import_filter` to reduce the initial import processing time.
[source,javascript]
----
include::{examplesdir}/getting-started/sync-gateway-config-import-filter.json[]
----
Configuration properties:

<1> The user's username that you created on the Couchbase Server Admin Console.
<2> The user's password that you created on the Couchbase Server Admin Console.
<3> The xref:shared-bucket-access.adoc[shared bucket access] feature allows Couchbase Server SDKs to also perform operations on this bucket.
<4> `num_index_replicas` is the number of index replicas stored in Couchbase Server, introduced with xref:indexing.adoc[GSI/N1QL indexing].
If you're running a single Couchbase Server node for development purposes the `num_index_replicas` must be set to `0`.
<5> Only import documents which have a `type` property equal to `mobile`.
--
====
* Start Sync Gateway from the command line, or if Sync Gateway is running in a service replace the configuration file and restart the service.
+
[source,bash]
----
~/Downloads/couchbase-sync-gateway/bin/sync_gateway ~/path/to/sync-gateway-config.json
----

* Run the application where Couchbase Lite is installed.

* To verify that documents have been replicated, you can:
** Monitor the Sync Gateway sequence number returned by the database endpoint (xref:sync-gateway::rest-api.adoc#/database/get\__db__[`+GET /{db}/+`]).
The sequence number increments for every change that happens on the Sync Gateway database.
** Query a document by ID on the Sync Gateway REST API (xref:sync-gateway::rest-api.adoc#/document/get\__db___doc_[`+GET /{db}/{id}+`]).
** Query a document from the Query Workbench on the Couchbase Server Console.

== Network Ports

Sync Gateway uses specific ports for communication with the outside world, mostly Couchbase Lite databases replicating to and from Sync Gateway.
The following table lists the ports used for different types of Sync Gateway network communication:

[cols="1,3"]
|===
|Port |Description

|4984
|Public port.
External HTTP port used for replication with Couchbase Lite databases and other applications accessing the REST API on the Internet.

The Public REST API is used for client replication. The default port for the Public REST API is 4984.

|4985
|Admin port.
Internal HTTP port for unrestricted access to the database and to run administrative tasks.

The Admin REST API is used to administer user accounts and roles. It can also be used to look at the contents of databases in superuser mode. The default port for the Admin REST API is 4985. By default, the Admin REST API is reachable only from localhost for safety reasons.
|===

The APIs are accessed on different TCP ports, which makes it easy to expose the Public REST API on port 4984 to endpoints while keeping the Admin REST API on port 4985 secure behind your firewall.

If you want to change the ports, you can do that in the configuration file.

* To change the Public REST API port, set the `interface` property in the configuration file.
* To change the Admin REST API port, set the `adminInterface` property in the configuration file.

The value of the property is a string consisting of a colon followed by a port number (for example, `:4985`).
You can also prepend a host name or numeric IP address before the colon to bind only to the network interface with that address.

As a useful special case, the IP address 127.0.0.1 binds to the loopback interface, making the port unreachable from any other host.
This is the default setting for the admin interface.
