= Release Notes
:page-status: {release-status-sgw} -- {release-comments-sgw}
:page-edition: Under development
:page-layout: article
:page-content-type: reference
:page-role: panes
:page-aliases: reelase-notes
:description: Sync Gateway Installation Document
:keywords: edge nosql api synchronization replication
// End of Page Definition Statements

include::shared-mobile::partial$_attributes-shared.adoc[]
include::ROOT:partial$_attributes-local.adoc[]
include::ROOT:partial$_page-index.adoc[]

[abstract]
--
This content provides release information pertaining to Sync Gateway {page-component-version} and subsequent maintenance releases.
--

[.panes__frames--auto.cols-4]
== Release {page-component-version}

.Quick Links
* <<Enhancements>> *|* <<Congiguration Changes,Config Changes>> *|* <<Support Notices>> *|* <<Known issues, Known Issues>> *|* <<Fixed at this Release,Fixed>>

.Release Date
* 99MMMYYYY

== Enhancements

NOTE: Still to be added

Excepteur eiusmod est aliqua est non quis id sint. Incididunt in deserunt ex sint. Laboris proident ea qui deserunt sint sint sunt minim sit. Id anim occaecat culpa non amet duis cupidatat sit sint cillum cillum pariatur mollit.

Occaecat consequat occaecat do velit nostrud cupidatat ex exercitation nostrud anim reprehenderit qui aute. Sunt nisi excepteur est esse enim excepteur ipsum laboris non nostrud consequat sunt ex duis. Amet veniam irure pariatur consequat deserunt quis ad irure incididunt ea. Consequat aliqua quis esse ex mollit do cillum reprehenderit dolor est et elit cupidatat. Minim aliquip Lorem exercitation sint esse commodo aliquip id eiusmod.

== Configuration Changes

This section identifies the changes to the Sync Gateway Configuration Schema for Release {page-component-version}

=== Structural Schema Changes

The replication configuration has moved.
Previously a top-level property, it is now defined within a database-specific property.
Note that any given database can still have multiple replications configured.

Constraint: SG-Replicate 2 does not support replication between two remote hosts via a third Sync Gateway.

=== Removed Properties

The following replication configuration properties are either removed from _ReplicationConfig_, or remain but are non-functional:

create_target::
_Non-functional_.
This remains in `ReplicationConfig` but is redundant for Couchbase Server-backed use cases.

proxy::
_Non-functional_.

doc_ids::
_Non-functional_.

//Present in ReplicationConfig but non-functional today.  If we decide to add support for doc_id-based replication filters, we should use filter/query_params.

source::
_Removed - redundant_.
+
This property is, implicitly, the database associated with the replication.

[[target-property,target]]
target::
_Removed - redundant_.
+
This property is replaced by the `<<remote-property>>` property.

async::
_Removed - redundant_.
+
Requests to `_replicate API` *always* run in async mode, now that the status of a completed one-shot replication is available in active_tasks.
+
This _REST-API-only_ parameter was formerly the method used to force a request to start without awaiting completion of one-shot replications (that is, to run asynchronuously).

changes_feed_limit::
_Removed - redundant_.

=== New Configuration Properties

The following new properties are added:

[[remote-property, remote]]
remote::
This property represents a database URL for the remote Sync Gateway.
To use another database hosted on this Sync Gateway, specify its full Sync Gateway database URL here.
+
This property replaces the former <<target-property>>.

direction::

Valid values are push, pull, and push_and_pull.

conflict_resolution_type::

Valid values are default, local_wins, remote_wins, custom

custom_conflict_resolver::

Javascript function for conflict resolution.  Only valid when conflict_resolution_type = custom

purge_on_removal::
Boolean value for whether channel removals should trigger purge
Defaults to false

enable_delta_sync::
Boolean value for whether to enable delta sync for this replication.

maximum_backoff_time::
Amount of time to keep retrying unreachable targets for
state

Replication state::
Possible values in replicationStatus response are stopping, stopped, starting, active
Valid values in configuration or in payload to replication endpoint are stopping, starting

=== Maintained Configuration Properties
The following replication configuration properties are maintained:

* continuous
* filter
* query_params

=== Modified Configuration Properties

The following replication configuration properties have changed:

cancel::
This property requests a running replication stop. It is valid *only* when using ReplicationConfig for _replicate REST API calls.
+
If defined in the configuration schema, it will log an error and prevent start up.
+
When used in the REST API, you must specify the `replication_id` of a running replication or the request will return an error.

== Support Notices

NOTE: Section not yet updated, may become an include from pn-supported-os.adoc

// https://issues.couchbase.com/browse/DOC-6462 Support Notices

//==== Sync Gateway

=== Deprecation Notices

.points to cover, include:
* https://issues.couchbase.com/browse/DOC-6461 Deprecation notices

* Deprecate pre-H2 replication DB configuration method https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e7cd22f#heading=h.u10lcuiyz5d0


=== End of Life Notices

SG Replicate 1.0 https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e7cd22f#heading=h.nwllc3an70af

=== Constraints

// https://issues.couchbase.com/browse/DOC-6462 Support Notices

* Replication between two remote databases https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e7cd22f#heading=h.nwllc3an70af


== Known Errors and Resolved Issues

=== {ke}

* Enim ipsum duis cillum pariatur.
* Enim ipsum duis cillum pariatur.
* Enim ipsum duis cillum pariatur.

=== {fixed}

* Enim ipsum duis cillum pariatur.
* Enim ipsum duis cillum pariatur.
* Enim ipsum duis cillum pariatur.


== Compatibility

NOTE: Section not yet updated, will likely be an include from compatibility.adoc

.Include notes on upgrading:
* In order to support SG-Replicate 2.0, all active nodes in active cluster must have min release version of Hydrogen.
+
Documentation: Need to call this out
* Sync Gateway (Hydrogen) will only  support 2.x versions of SG-Replicate.
* include table from here: https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e873940#


https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e7cd22f#heading=h.nf0vv4c38gr


[.panes__frames--auto.cols-3]
== Related Content

.How-to:
* xref:{component-sgw}::upgrade.adoc[Upgrading to {page-component-version}]

.Learn more:
* xref:{component-sgw}::pn-compatibility.adoc[Compatibility]
* xref:{component-sgw}::pn-supported-os.adoc[Supported OS]
* xref:{component-sgw}::pn-release-notes-archive.adoc[Release Note Archives]

.Dive Deeper ...
* link:{url-cb-tutorials}[Tutorials]
* link:{url-cb-blog-sgw}[Blog]
* link:{url-cb-Forum}[Forum]



