= Inter-Cluster Replication
:page-layout: article
:page-status: {release-status} -- {release-comments}
:page-edition: Under Develoment
:page-roles:
include::partial$_attributes-local.adoc[]
:xref-pfx-sgw: {xref-pfx-sgw}:
include::partial$_glossary-links.adoc[]

ifndef::releaseStatus[:releaseStatus!:]
ifeval::["{releaseStatus}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--
Create an overview of the Sync Gateway replication process

.points to include

* replicator diagram https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit#heading=h.33gfct4o4z8t


High level intro with links to appropriate details topics

Document replication concepts and use-cases
High-availability sync-gateway cluster replication
Persistent vs Transient replication types
Replication use cases:
mobile cluster replications
cloud-edge/hub-spoke replication
--
endif::[]

[abstract]
--
This content provides an overview of, and introduction to, Sync Gateway to Sync Gateway replication. Inter-cluster replication, uses SG Replicate protocol to enable replication between mobile clusters. That is, for example between a hub and its spoke clusters.
--

== Use Cases

Couchbase Sync Gateway supports inter-cluster replication, an increasingly important enterprise-level requirement that
supports _{glos-term-cloud-to-edge} synchronization_ use cases, where data changes must be synchronized between a centralized cloud cluster and a large number of edge clusters whilst still enforcing fine grained access control.

Inter-cluster repliaction provides the ability to run replications between:

* Sync Gateway clusters
* Active mobile clusters.

SG-Replicate 2.0 is the protocol that supports this use-case. It is an integral part of Sync Gateway, acting as the _{glos-term-active-replicator}_, pulling changes from a data source and pushing them to a target.

All documents pass through the target Sync Gateway's _{glos-term-sync-function}_ instance, ensuring that access rules are honored.

In the architecture diagram below, any changes that users/systems make on either Sync Gateway instance will be replicated to the other Sync Gateway instance.

.Inter-cluster cloud-to-edge synchronzation
image::icr-cloud-to-edge.svg[]







NOTE: A _Sync Gateway database_ can be considered a namespace for documents, the data is *always* stored in Couchbase Server.

== Alternative Methods

xref:server:manage:manage-xdcr/xdcr-management-overview.adoc[XDCR] (cross data centre replication) is the Couchbase Server API to replicate between Couchbase Server clusters.
Both XDCR and SG Replicate can be used to keep clusters in different data centres in sync.
However, SG Replicate was designed specifically for Couchbase Mobile deployments and must be used for replication between mobile clusters.

== Features

* {xref-sgw-pg-icr-high-availability} (HA)
* {xref-sgw-pg-icr-delta-sync} option
* Replicates via the Sync Gateway REST API (see: {xref-sgw-pg-adv-rest-api-client})
* Scalability
* JSON configuration to specify replications
* Supports multiple replications running concurrently
* Supports _{glos-term-persistent-replication}_ and _{glos-term-transient-replication}_
* Leverages the full duplex nature of websockets to support push and pull from a single connection
* Does not store anything persistently
* Stateless -- can be interrupted/restarted anytime without negative side effects
* Can specify which channel(s) to sync
* Supports Primary/Primary and Primary/Secondary topologies

== Limitations

* Can only replicate SG databases that are hosted on recent versions of Sync Gateway (after commit 50d30eb3d on March 7, 2014)
* In deployments with multiple Sync Gateway nodes, only _one_ of the Sync Gateways should be configured for replications.
If multiple Sync Gateways are configured for replications, it could substantially increase the amount of duplicate work, and therefore should be avoided.
The limitation is that the system is not guaranteed to be Highly Available: if the Sync Gateway that is chosen to drive the replication goes down or is otherwise removed from the system, then the replications will stop.
* Replication between Sync Gateway databases doesn't support automatic conflict resolution even when the no-conflicts mode is enabled (i.e xref:config-properties.adoc#databases-foo_db-allow_conflicts["allow_conflicts": false]).
When running two Sync Gateway clusters with the no-conflicts mode enabled, cross-cluster document conflicts will result in that document no longer being replicated.
Deployments  must implement a custom conflict resolver in an external app as specified xref:resolving-conflicts.adoc[here].
To avoid this, the application must ensure concurrent, cross-cluster updates are not made to a given document.

