= Glossary
:page-status: {release-status-sgw} -- {release-comments-sgw}
:page-edition: Under development
:page-layout: article
:page-content-type: reference
:page-role: -toc
:page-aliases: glossary
:description: Sync Gateway Glossary of Terms
:keywords: edge nosql api synchronization replication
// End of Page Definition Statements

include::shared-mobile::partial$_attributes-shared.adoc[]
include::ROOT:partial$_attributes-local.adoc[]

// Glosary entry name tag format:
//  {component} = sgw-
//  {namespace} = eg. access-control (acc) replication (repl), api, conflicts (conf), indexing (ndx) etc
//  {sub-space} = eg. user, document, role, channel, sync
//  {name} = free-from

:goto-index: Back to <<index>>


[[index]]
=== Index
[.pane__frame--blue]
<<A>>  |  <<B>>  |  <<C>>  |  <<D>>  |  <<E>>  |  <<F>>  |  <<G>>  |  <<H>>  |  <<I>>  |  <<J>>  |  <<K>>  |  <<L>>  |  <<M>>  |  <<N>>  |  <<O>>  |  <<P>>  |  <<Q>>  |  <<R>>  |  <<S>>  |  <<T>>  |  <<U>>  |  <<V>>  |  <<W>>  |  <<X>>  |  <<Y>>  |  <<Z>>

== A

[[active-replicator]]
Active replicator::
// tag::sgw-icr-active-replicator-full[]
// tag::sgw-icr-active-replicator[]
The term _active replicator_, refers to the Sync Gateway endpoint that initiates the replication connection.
That is, it s the Sync Gateway where the replicators are configured and from which the changes are pushed.
// end::sgw-icr-active-replicator[]
+
* _Synonym(s)_: active sync gateway
* _SGW Component_: Inter-cluster replication
* _Related Term(s)_: <<passive-replicator, Passive replicator>>
* _Read More_: {xref-sgw-pg-icr-overview}
// end::sgw-icr-active-replicator-full[]

[[auto-conflict-resolution]]
Automatic conflict resolution::
// tag::sgw-conf-res-auto-resolution[]
The process by which conflicts are automatically resolved by the system.
Optional feature in xref:couchbase-lite::swift.adoc#handling-conflicts[Couchbase Lite 2.0 and above].
// end::sgw-conf-res-auto-resolution[]

{goto-index}

== C

[[cloud-to-edge]]
Cloud-to-Edge Sync::
// tag::sgw-cloud-to-edge-full[]
// tag::sgw-cloud-to-edge-def[]
// tag::sgw-cloud-to-edge[]
The term _cloud-to-edge_ refers to the multi-cloud deployment mode commonly know as _ship-to-shore_ or _hub-and-spoke_.
Cloud-to-edge synchroization scenarios typically involve a hierarchy of couchbase mobile clusters, within which a large number of edge clusters sync with one or more clusters in cloud data centers.
// end::sgw-cloud-to-edge[]
+
Each edge can operate autonomously without network connectivity to the cloud data centers.
The _edge_ could be, for example a group of retail stores, ships at sea or distribution hubs.
The number of edges can range from a few hundred to several thousand.
// end::sgw-cloud-to-edge-def[]
+
* _Synonym(s)_: ship-to-shore sync, hub-and-spoke sync
* _SGW Component_: Inter-cluster replication
* _Related Term(s)_:
* _Read More_: {xref-sgw-pg-icr-overview}
// end::sgw-cloud-to-edge-full[]

{goto-index}

//== D

//{goto-index}

== I

Inter-cluster Replication::
// tag::sgw-inter-cluster-replication-full[]
// tag::sgw-inter-cluster-replication-def[]
// tag::sgw-inter-cluster-replication[]
The term _inter-cluster replication_ refers to replication between
two Sync Gateway clusters and-or between Active mobile clusters.
// tag::sgw-inter-cluster-replication[]
+
Inter-cluster replication within Sync Gateway is delivered by the SG-Replicate 2.0 protocol, which enables a Sync Gateway replicator to act as the _{glos-term-active-replicator}_, pulling changes from a data source and pushing them to a target.
// tag::sgw-inter-cluster-replication-def[]
// tag::sgw-inter-cluster-replication-full[]

{goto-index}

== L

Leaf revision::
// tag::sgw-conf-res-leaf-revision[]
A Leaf revision is the last Document Revision in a series of changes.
Documents may have multiple Leaf Revisions (aka Conflict Revisions) due to concurrent updates.
// end::sgw-conf-res-leaf-revision[]

{goto-index}

== N

No conflicts mode::
// tag::sgw-conf-res-no-conflicts[]
No conflicts mode is the process by which write operations that would result in a conflict are rejected by the system.
It is an optional feature in xref:couchbase-lite::swift.adoc#handling-conflicts[Couchbase Lite 2.0 and above] and xref:config-properties.adoc#databases-foo_db-allow_conflicts[Sync Gateway 2.0 and above].
// end::sgw-conf-res-no-conflicts[]

{goto-index}

== P

[[passive-replicator]]
Passive replicator::
// tag::sgw-icr-passive-replicator-full[]
// tag::sgw-icr-passive-replicator[]
The term _passive replicator_, refers to the Sync Gateway endpoint that receives an incoming replication connection.
// end::sgw-icr-passive-replicator[]
+
* _Synonym(s)_: passive sync gateway
* _Related Term(s)_: <<active-replicator, Active replicator>>
* _SGW Component_: Inter-cluster replication
* _Read More_: {xref-sgw-pg-icr-overview}
// end::sgw-icr-passive-replicator-full[]

[[persistent-replication]]
Persistent Replication::
// tag::sgw-icr-persistent-replication-full[]
// tag::sgw-icr-persistent-replication-def[]
// tag::sgw-icr-persistent-replication[]
The term _Persistent replication_ refers to replications that survive Sync Gateway restarts.
All replications are persisted by default unless explicitly flagged as not.
// end::sgw-icr-persistent-replication[]
Persistent replication is defined in the configuration file sync-gateway.json (see sync-gateway::config-properties.adoc).
It is started automatically and survives restarts.
The recommended method of defining a persistent replication is by using the configuration file.
With SG Replicate 2.0 you can configure all nodes with the replicators.
// end::sgw-icr-persistent-replication-def[]
+
* _Synonym(s)_: continuous replication
* _Related Term(s)_:
** <<transient-replication, Transient replication>>
** <<transient-replication, Adhoc replication>>
* _SGW Component_: Inter-cluster replication
* _Read More_: {xref-sgw-pg-icr-overview}
// end::sgw-icr-persistent-replication-full[]

{goto-index}

== R

Revision pruning::
// tag::sgw-conf-res-revision-pruning[]
Revision Pruning is the process that deletes the metadata and/or JSON bodies associated with old non-leaf revisions.
Leaf revisions are not impacted.
// end::sgw-conf-res-revision-pruning[]

{goto-index}

== S

[[sync-function]]
Sync Function::
// tag::sgw-icr-sync-function[]
Aliquip cillum aliquip ad sit tempor labore qui non voluptate qui nisi proident. Reprehenderit eu labore non ex ullamco incididunt elit. Minim aliquip dolore laboris non. Et id exercitation et quis duis officia aliquip consequat eu aliqua culpa esse.
// end::sgw-icr-sync-function[]

== T

Tombstone revision::
// tag::sgw-conf-res-tombstone[]
A Tombstone Revision is a document revision that contains only the document ID, a revision ID and the `_deleted: true` key value pair. It acts as the record of a deleted item.
+
Tombstone revisions are created to allow all devices to see that a document has been deleted - particularly in the case of devices that may not be online continuously and therefore not syncing regularly.
+
[source,json]
----
{
  "_deleted": true,
  "_id": "foobar",
  "_rev": "3-db962c6d93c3f1720cc7d3b6e50ac9df"
}
----
Mentioned in:
* xref:managing-tombstones.adoc[Managing Tombstones]
* xref:shared-bucket-access.adoc#metadata-purge-interval[Metadata Purge Interval]
* xref:config-properties.adoc#databases-foo_db-enable_shared_bucket_access[$dbname.enable_shared_bucket_access]
* xref:server:learn:buckets-memory-and-storage/storage.adoc#tombstones[Server Tombstones]
// end::sgw-conf-res-tombstone[]

[[transient-replication]]
Transient Replication::
// tag::sgw-icr-transient-replication-full[]
// tag::sgw-icr-transient-replication-def[]
// tag::sgw-icr-transient-replication[]
The term _transient replication_ refers to replications that run once only (whenever manually initiated).
These are useful when it is necessary to do one off replication or for troubleshooting.
They do not survive Sync Gateway restarts.
// end::sgw-icr-transient-replication[]
+
Other useful use cases include:

* Starting a replication on-demand, for instance a replication that needs to be scheduled to be run at midnight every Thursday.
In this case, it is likely that there is an automation script that schedules the adhoc replication on a predefined schedule.
* Or deploying an emergency one-time update that needs to be pushed out to all edge clusters from primary data clusters.
// end::sgw-icr-transient-replication-def[]

+
Context:

* _Synonym(s)_: adhoc replication
* _Related Term(s)_:
** <<persistent-replication, Persistent replication>>
** <<continuous-replication, Continuous replication>>
* _SGW Component_: Inter-cluster replication
* _Read More_: {xref-sgw-pg-icr-overview}
// end::sgw-icr-transient-replication-full[]

{goto-index}
